language: objective-c
compiler:
  - clang
env:
  matrix:
    - OPENFOAM_TEST_VERSION='2.1.1'
    - OPENFOAM_TEST_VERSION='2.1.x'
    - OPENFOAM_TEST_VERSION='2.2.2'
    - OPENFOAM_TEST_VERSION='2.2.x'
    - OPENFOAM_TEST_VERSION='2.3.0'
    - OPENFOAM_TEST_VERSION='2.3.x'
before_install:
  - ./script/ci/before_install.sh $OPENFOAM_TEST_VERSION
install:
  - ./script/ci/install.sh $OPENFOAM_TEST_VERSION
before_script:
  - ./script/ci/before_test.sh $OPENFOAM_TEST_VERSION
script:
  - ./script/ci/test.sh $OPENFOAM_TEST_VERSION
os:
  - osx
