language: cpp
os:
  - osx
compiler:
  - clang
env:
  - OPENFOAM_TEST_VERSION='2.4.0'
  - OPENFOAM_TEST_VERSION='2.4.x'
  - OPENFOAM_TEST_VERSION='3.0.1'
  - OPENFOAM_TEST_VERSION='3.0.x'
before_install:
  - for f in $(brew list); do brew uninstall --force $f; done
  - brew tap homebrew/science
  - brew update
  - brew install openmpi
  - brew install scotch
  - brew install metis
  - brew install parmetis
  - brew install boost
  - brew install cgal
  - hdiutil create -size 8g -type SPARSEBUNDLE -fs HFSX -volname OpenFOAM -fsargs -s "$HOME/OpenFOAM.sparsebundle"
  - mkdir -p "$HOME/OpenFOAM"
  - hdiutil attach -mountpoint "$HOME/OpenFOAM" "$HOME/OpenFOAM.sparsebundle"
install:
  - ./script/ci/prepare.sh $OPENFOAM_TEST_VERSION
  - cd "$HOME/OpenFOAM/OpenFOAM-$OPENFOAM_TEST_VERSION"
  - source etc/bashrc
  - (cd wmake/src && make)
  - cd src
  - makeType=libso
  - wmakePrintBuild -check || /bin/rm -f OpenFOAM/Make/*/global.? 2>/dev/null
  - wmakeLnInclude OpenFOAM
  - wmakeLnInclude OSspecific/${WM_OSTYPE:-POSIX}
  - Pstream/Allwmake $*
  - OSspecific/${WM_OSTYPE:-POSIX}/Allwmake $*
  - wmake libso OpenFOAM
  - wmake libso fileFormats
  - wmake libso surfMesh
  - wmake libso triSurface
  - wmake libso meshTools
  - wmake libso edgeMesh
  - parallel/decompose/AllwmakeLnInclude
  - dummyThirdParty/Allwmake $*
  - wmake libso finiteVolume
  - wmake libso lagrangian/basic
  - wmake libso lagrangian/distributionModels
  - wmake libso genericPatchFields
  - parallel/Allwmake $*
  - renumber/Allwmake $*
  - wmake $makeType conversion
  - wmake $makeType sampling
  - wmake $makeType mesh/extrudeModel
  - wmake $makeType dynamicMesh
  - wmake $makeType dynamicFvMesh
  - wmake $makeType topoChangerFvMesh
  - wmake $makeType ODE
  - wmake $makeType randomProcesses
  - thermophysicalModels/Allwmake $*
  - transportModels/Allwmake $*
  - turbulenceModels/Allwmake $*
  - TurbulenceModels/Allwmake $*
  - wmake $makeType combustionModels
  - regionModels/Allwmake $*
  - lagrangian/Allwmake $*
  - mesh/Allwmake $*
  - fvAgglomerationMethods/Allwmake $*
  - wmake $makeType fvMotionSolver
  - wmake $makeType engine
  - wmake $makeType fvOptions
  - wmake $makeType regionCoupled
  - postProcessing/Allwmake $*
  - wmake $makeType sixDoFRigidBodyMotion
  - cd ..
  - cd applications
  - cd utilities && wmake all && cd ..
  - cd solvers && wmake all && cd ..
before_script:
  - ./script/ci/before_test.sh $OPENFOAM_TEST_VERSION
script:
  - ./script/ci/test.sh $OPENFOAM_TEST_VERSION

